# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 8, 6, 12, 18, 54, 744808, tzinfo=utc)),
        ),
    ]
