# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170806_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 8, 7, 8, 28, 17, 458620, tzinfo=utc)),
        ),
    ]
